SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `building_facade_config`;
TRUNCATE TABLE `device_cell`;
TRUNCATE TABLE `room_cell`;
TRUNCATE TABLE `people_count_hourly`;
TRUNCATE TABLE `room`;
TRUNCATE TABLE `building_cell`;
TRUNCATE TABLE `floor`;
TRUNCATE TABLE `building`;
SET FOREIGN_KEY_CHECKS=1;
